stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
    - main
  script:
    - kubectl apply -f ./manifests
  environment:
    name: onpremise
    kubernetes:
      namespace: ${K8S_NAMESPACE}
