apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-credentials-renewer
spec:
  schedule: "55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-credentials-renewer
          restartPolicy: OnFailure
          containers:
            - name: ecr-credentials-renewer
              image: ${CONTAINER_IMAGE_TAGGED}
              env:
                - name: HTTP_PROXY
                  value: http://172.16.105.13:8118
                - name: HTTPS_PROXY
                  value: http://172.16.105.13:8118
              envFrom:
                - secretRef:
                    name: environment-variables

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-credentials-renewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecr-credentials-renewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ecr-credentials-renewer
    namespace: moreillon
