apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-credentials-renewer
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-credentials-renewer
          restartPolicy: OnFailure
          volumes:
            - name: ecr-credentials-renewer
              configMap:
                name: ecr-credentials-renewer
          containers:
            - name: kubectl
              image: moreillon/ci-dind:4bca50d7
              command:
                - /bin/bash
                - /script.sh
              volumeMounts:
                - mountPath: /script.sh
                  name: ecr-credentials-renewer
                  subPath: script.sh

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-credentials-renewer
data:
  script.sh: |
    kubectl create secret docker-registry ecr-credentials \
      --docker-server=732469118990.dkr.ecr.ap-northeast-1.amazonaws.com \
      --docker-username=AWS \
      --docker-password $(curl http://10.115.1.100:30990/password) \
      --dry-run=client -o yaml \
      | kubectl apply -f - \

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-credentials-renewer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ecr-credentials-renewer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecr-credentials-renewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ecr-credentials-renewer
subjects:
  - kind: ServiceAccount
    name: ecr-credentials-renewer
