apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-credentials-renewer
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ecr-credentials-renewer
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: moreillon/ci-dind:4bca50d7
              command:
                - /bin/bash
                - /script.sh
              volumeMounts:
                - mountPath: /script.sh
                  name: ecr-credentials-renewer
                  subPath: script.sh
          volumes:
            - name: ecr-credentials-renewer
              configMap:
                name: ecr-credentials-renewer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-credentials-renewer
data:
  script.sh: |
    #!/bin/bash

    secretName='ecr-credentials'
    namespaces=$(kubectl get ns --no-headers |  awk '{print $1}')
    password=$(curl http://10.115.1.100:30990/password)

    for namespace in $namespaces;
    do

      isException=false

      # TODO: have this as env var
      for ex in 'kube-system' 'ingress' 'kube-public' 'kube-node-lease';
      do
        if [ "$ex" == "$namespace" ]; 
        then
          isException=true
        fi
      done

      if ! $isException ;
      then
        echo "Applying secret for namesapce $namespace"
        kubectl create secret docker-registry $secretName \
          --docker-server=732469118990.dkr.ecr.ap-northeast-1.amazonaws.com \
          --docker-username=AWS \
          --docker-password $password \
          --dry-run=client -o yaml \
          | kubectl apply -n $namespace -f - 
      fi
      
    done
